---
# Main configuration

homeassistant:
  # Default
  name: Home
  elevation: 0
  unit_system: metric
  time_zone: Europe/Paris

  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  
  # Lets me customize individual entities
  customize: !include_dir_merge_named ../customizations/entities
  