---
# The HomeKit component allows you to forward entities from Home Assistant
# to Apple HomeKit, so they can be controlled from Apple’s Home app and Siri.
#
# https://www.home-assistant.io/integrations/homekit
#
homekit:
  # Start the HomeKit Server automatically.
  # I have a Z-Wave network, but since Home Assistant restores entities,
  # we don't have to wait for it (like we did in the past).
  auto_start: false

  # The default: "Home Assistant Bridge", I like it to be just "Home Assistant"
  name: Home Assistant 🍓

  # Configuration for specific entities. Allows customization of names and types
  # These are imported from another folder, to decouple them from the packages.
  # entity_cosnfig: 
  #   !include_dir_named ../assistants/siri

  # Filters for entities to be included / excluded from HomeKit.
  filter:
    include_entities:
      - binary_sensor.main_door_open_sensor
      - binary_sensor.octoprint_actual_bed_temp
      - sensor.octoprint_actual_tool0_temp
      - sensor.speedtest_upload
      - sensor.speedtest_download
  
  entity_config:
    sensor.speedtest_download:
      name: SpeedTest Download
    sensor.speedtest_upload:
      name: SpeedTest Upload
    binary_sensor.living_room_motion:
      name: Capteur ouverture porte entree
      linked_battery_sensor: sensor.main_door_open_sensor_battery_level
      low_battery_threshold: 31
    sensor.octoprint_actual_bed_temp:
      name: Temperature bed
    sensor.octoprint_actual_tool0_temp:
      name: Temperature tete

