---
# OctoPrint is a web interface for your 3D printer. 
# This is the main integration to integrate OctoPrint sensors.
#
# https://www.home-assistant.io/integrations/octoprint/
# https://community.home-assistant.io/t/octoprint-setup-ui-scripts-and-automations/192279

octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_api_key
  bed: true
  number_of_tools: 2
