---

# The speedtestdotnet integration uses the Speedtest.net
# Web service to measure network bandwidth performance.
#
# Configuraion: https://www.home-assistant.io/integrations/speedtestdotnet/
#

speedtestdotnet:
  scan_interval:
    minutes: 30
