---
platform: generic
name: car
still_image_url: https://static-maps.yandex.ru/1.x/?lang=en-US&ll={{ states.sensor.car_vehicle_data.attributes.location.latitude }},{{ states.sensor.car_vehicle_data.attributes.location.longitude }}&z=13&l=map,skl&size=600,300