---
# Xee car captor
# How to buy : https://amzn.to/2LUn95x
# How to configure : https://medium.com/@redteamwins/how-i-integrated-a-xee-connected-car-in-home-assistant-dd609a91213c

platform: rest
resource: !secret xee_resource
method: GET
name: car_vehicle_data
headers:
  Authorization: !secret xee_token
json_attributes: 
  - signals
  - location
  - updatedAt
value_template: ''
scan_interval: 300